const wines = [
  {
    "id": 1,
    "name": "Tempranillo Estate",
    "image": "https://www.bodegasescondidas.com.ar/wp-content/uploads/2022/01/Berrinche-Tempranillo-de-Finca.JPG-510x510.png",
    "description": "A red wine made from Tempranillo, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2021,
    "winery": "Robert Mondavi",
    "country": "Australia",
    "grape": "Tempranillo",
    "price": 30
  },
  {
    "id": 2,
    "name": "Merlot Select",
    "image": "https://http2.mlstatic.com/D_NQ_NP_660066-MLA77188302268_072024-O.webp",
    "description": "A red wine made from Merlot, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2016,
    "winery": "Gaja",
    "country": "France",
    "grape": "Merlot",
    "price": 56
  },
  {
    "id": 3,
    "name": "Merlot Reserve",
    "image": "https://i0.wp.com/trescumbres.wine/wp-content/uploads/2020/08/lg-merlot-reserva.jpg?fit=1000%2C1000&ssl=1",
    "description": "A red wine made from Merlot, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2019,
    "winery": "Gaja",
    "country": "Australia",
    "grape": "Merlot",
    "price": 57
  },
  {
    "id": 4,
    "name": "Cabernet Sauvignon Reserve",
    "image": "https://lasperdicesar.vtexassets.com/arquivos/ids/155792-800-800?v=638810113141070000&width=800&height=800&aspect=true",
    "description": "A red wine made from Cabernet Sauvignon, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2012,
    "winery": "Antinori",
    "country": "Argentina",
    "grape": "Cabernet Sauvignon",
    "price": 45
  },
  {
    "id": 5,
    "name": "Cabernet Sauvignon Estate",
    "image": "https://tienda.aldosvinoteca.com/cdn/shop/files/casarena_estate_cabernet_sauvig_r_copia_1_69492dbc-5f0c-4a45-8c9a-20adae0bc847.jpg?v=1718129350",
    "description": "A red wine made from Cabernet Sauvignon, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2020,
    "winery": "Gaja",
    "country": "Chile",
    "grape": "Cabernet Sauvignon",
    "price": 16
  },
  {
    "id": 6,
    "name": "Cabernet Sauvignon Select",
    "image": "https://winesupply.vtexassets.com/arquivos/ids/157137-800-auto?v=637746648362900000&width=800&height=auto&aspect=true",
    "description": "A red wine made from Cabernet Sauvignon, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2017,
    "winery": "Gaja",
    "country": "Chile",
    "grape": "Cabernet Sauvignon",
    "price": 33
  },
  {
    "id": 7,
    "name": "Merlot Estate",
    "image": "https://tienda.aldosvinoteca.com/cdn/shop/files/bianco_canale_53959b75-9bb4-4e81-81cf-5c6023ff4616.jpg?v=1718129821",
    "description": "A red wine made from Merlot, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2012,
    "winery": "Penfolds",
    "country": "Spain",
    "grape": "Merlot",
    "price": 57
  },
  {
    "id": 8,
    "name": "Cabernet Sauvignon Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=8",
    "description": "A red wine made from Cabernet Sauvignon, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2022,
    "winery": "Gaja",
    "country": "Australia",
    "grape": "Cabernet Sauvignon",
    "price": 31
  },
  {
    "id": 9,
    "name": "Cabernet Sauvignon Classic",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=9",
    "description": "A red wine made from Cabernet Sauvignon, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2014,
    "winery": "Robert Mondavi",
    "country": "USA",
    "grape": "Cabernet Sauvignon",
    "price": 41
  },
  {
    "id": 10,
    "name": "Malbec Select",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=10",
    "description": "A red wine made from Malbec, known for its balanced flavor and aroma.",
    "category": "red",
    "year": 2021,
    "winery": "Gaja",
    "country": "Australia",
    "grape": "Malbec",
    "price": 22
  },
  {
    "id": 11,
    "name": "Sauvignon Blanc Select",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=11",
    "description": "A white wine made from Sauvignon Blanc, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2015,
    "winery": "Robert Mondavi",
    "country": "Italy",
    "grape": "Sauvignon Blanc",
    "price": 29
  },
  {
    "id": 12,
    "name": "Riesling Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=12",
    "description": "A white wine made from Riesling, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2020,
    "winery": "Antinori",
    "country": "Australia",
    "grape": "Riesling",
    "price": 19
  },
  {
    "id": 13,
    "name": "Sauvignon Blanc Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=13",
    "description": "A white wine made from Sauvignon Blanc, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2012,
    "winery": "Gaja",
    "country": "USA",
    "grape": "Sauvignon Blanc",
    "price": 57
  },
  {
    "id": 14,
    "name": "Riesling Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=14",
    "description": "A white wine made from Riesling, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2021,
    "winery": "Beringer",
    "country": "Chile",
    "grape": "Riesling",
    "price": 49
  },
  {
    "id": 15,
    "name": "Sauvignon Blanc Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=15",
    "description": "A white wine made from Sauvignon Blanc, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2014,
    "winery": "Gaja",
    "country": "Argentina",
    "grape": "Sauvignon Blanc",
    "price": 40
  },
  {
    "id": 16,
    "name": "Chardonnay Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=16",
    "description": "A white wine made from Chardonnay, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2014,
    "winery": "Robert Mondavi",
    "country": "Chile",
    "grape": "Chardonnay",
    "price": 43
  },
  {
    "id": 17,
    "name": "Chardonnay Classic",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=17",
    "description": "A white wine made from Chardonnay, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2018,
    "winery": "Beringer",
    "country": "Australia",
    "grape": "Chardonnay",
    "price": 17
  },
  {
    "id": 18,
    "name": "Sauvignon Blanc Estate",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=18",
    "description": "A white wine made from Sauvignon Blanc, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2022,
    "winery": "Gaja",
    "country": "Chile",
    "grape": "Sauvignon Blanc",
    "price": 24
  },
  {
    "id": 19,
    "name": "Pinot Grigio Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=19",
    "description": "A white wine made from Pinot Grigio, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2021,
    "winery": "Gaja",
    "country": "France",
    "grape": "Pinot Grigio",
    "price": 59
  },
  {
    "id": 20,
    "name": "Viognier Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=20",
    "description": "A white wine made from Viognier, known for its balanced flavor and aroma.",
    "category": "white",
    "year": 2018,
    "winery": "Penfolds",
    "country": "Spain",
    "grape": "Viognier",
    "price": 59
  },
  {
    "id": 21,
    "name": "Champagne Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=21",
    "description": "A sparkling wine made from Champagne, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2016,
    "winery": "Concha y Toro",
    "country": "France",
    "grape": "Champagne",
    "price": 41
  },
  {
    "id": 22,
    "name": "Prosecco Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=22",
    "description": "A sparkling wine made from Prosecco, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2013,
    "winery": "Antinori",
    "country": "Australia",
    "grape": "Prosecco",
    "price": 24
  },
  {
    "id": 23,
    "name": "Cava Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=23",
    "description": "A sparkling wine made from Cava, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2016,
    "winery": "Concha y Toro",
    "country": "Argentina",
    "grape": "Cava",
    "price": 24
  },
  {
    "id": 24,
    "name": "Sparkling Ros\u00e9 Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=24",
    "description": "A sparkling wine made from Sparkling Ros\u00e9, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2012,
    "winery": "Beringer",
    "country": "Spain",
    "grape": "Sparkling Ros\u00e9",
    "price": 35
  },
  {
    "id": 25,
    "name": "Prosecco Classic",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=25",
    "description": "A sparkling wine made from Prosecco, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2018,
    "winery": "Torres",
    "country": "Australia",
    "grape": "Prosecco",
    "price": 34
  },
  {
    "id": 26,
    "name": "Franciacorta Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=26",
    "description": "A sparkling wine made from Franciacorta, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2015,
    "winery": "Beringer",
    "country": "Italy",
    "grape": "Franciacorta",
    "price": 20
  },
  {
    "id": 27,
    "name": "Cava Estate",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=27",
    "description": "A sparkling wine made from Cava, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2021,
    "winery": "Torres",
    "country": "Chile",
    "grape": "Cava",
    "price": 16
  },
  {
    "id": 28,
    "name": "Champagne Classic",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=28",
    "description": "A sparkling wine made from Champagne, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2012,
    "winery": "Torres",
    "country": "Spain",
    "grape": "Champagne",
    "price": 58
  },
  {
    "id": 29,
    "name": "Prosecco Estate",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=29",
    "description": "A sparkling wine made from Prosecco, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2013,
    "winery": "Concha y Toro",
    "country": "Australia",
    "grape": "Prosecco",
    "price": 13
  },
  {
    "id": 30,
    "name": "Champagne Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=30",
    "description": "A sparkling wine made from Champagne, known for its balanced flavor and aroma.",
    "category": "sparkling",
    "year": 2018,
    "winery": "Robert Mondavi",
    "country": "Italy",
    "grape": "Champagne",
    "price": 42
  },
    {
    "id": 31,
    "name": "Rosé Estate",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=31",
    "description": "A fresh and vibrant rosé wine, perfect for summer afternoons.",
    "category": "rosé",
    "year": 2022,
    "winery": "Chateau Miraval",
    "country": "France",
    "grape": "Grenache",
    "price": 28
  },
  {
    "id": 32,
    "name": "Pink Pinot",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=32",
    "description": "A delicate rosé with hints of strawberry and rose petals.",
    "category": "rosé",
    "year": 2021,
    "winery": "Whispering Angel",
    "country": "France",
    "grape": "Pinot Noir",
    "price": 35
  },
  {
    "id": 33,
    "name": "Blush Rosé",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=33",
    "description": "A light and fruity rosé, balanced and refreshing.",
    "category": "rosé",
    "year": 2020,
    "winery": "Beringer",
    "country": "USA",
    "grape": "Zinfandel",
    "price": 22
  },
  {
    "id": 34,
    "name": "Sunset Rosé",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=34",
    "description": "Bright and aromatic rosé with notes of citrus and berries.",
    "category": "rosé",
    "year": 2019,
    "winery": "Torres",
    "country": "Spain",
    "grape": "Tempranillo",
    "price": 25
  },
  {
    "id": 35,
    "name": "Rosé Reserve",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=35",
    "description": "Elegant rosé with floral aroma and a crisp finish.",
    "category": "rosé",
    "year": 2021,
    "winery": "Antinori",
    "country": "Italy",
    "grape": "Sangiovese",
    "price": 30
  },
  {
    "id": 36,
    "name": "Garden Rosé",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=36",
    "description": "Fresh and juicy rosé, ideal for outdoor gatherings.",
    "category": "rosé",
    "year": 2022,
    "winery": "Robert Mondavi",
    "country": "USA",
    "grape": "Syrah",
    "price": 27
  },
  {
    "id": 37,
    "name": "Berry Rosé",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=37",
    "description": "Rosé with intense berry flavors and a smooth finish.",
    "category": "rosé",
    "year": 2020,
    "winery": "Gaja",
    "country": "Italy",
    "grape": "Nebbiolo",
    "price": 34
  },
  {
    "id": 38,
    "name": "Classic Rosé",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=38",
    "description": "A classic dry rosé with balanced acidity and fruit notes.",
    "category": "rosé",
    "year": 2018,
    "winery": "Penfolds",
    "country": "Australia",
    "grape": "Shiraz",
    "price": 29
  },
  {
    "id": 39,
    "name": "Rosé Vintage",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=39",
    "description": "Vintage rosé with delicate aromas and refreshing taste.",
    "category": "rosé",
    "year": 2017,
    "winery": "Beringer",
    "country": "Chile",
    "grape": "Cabernet Franc",
    "price": 26
  },
  {
    "id": 40,
    "name": "Summer Rosé",
    "image": "https://images.unsplash.com/photo-1600180758890-bb2d8c8919e3?ixid=40",
    "description": "Light rosé, perfect for summer days with notes of watermelon.",
    "category": "rosé",
    "year": 2022,
    "winery": "Concha y Toro",
    "country": "Chile",
    "grape": "Carignan",
    "price": 24
  }
];

export default wines;
