const wines = [
    {
        id: 1,
        name: "Tempranillo Estate",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Tempranillo, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2021,
        winery: "Robert Mondavi",
        country: "Australia",
        grape: "Tempranillo",
        price: 30,
    },
    {
        id: 2,
        name: "Merlot Select",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Merlot, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2016,
        winery: "Gaja",
        country: "France",
        grape: "Merlot",
        price: 56,
    },
    {
        id: 3,
        name: "Merlot Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Merlot, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2019,
        winery: "Gaja",
        country: "Australia",
        grape: "Merlot",
        price: 57,
    },
    {
        id: 4,
        name: "Cabernet Sauvignon Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Cabernet Sauvignon, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2012,
        winery: "Antinori",
        country: "Argentina",
        grape: "Cabernet Sauvignon",
        price: 45,
    },
    {
        id: 5,
        name: "Cabernet Sauvignon Estate",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Cabernet Sauvignon, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2020,
        winery: "Gaja",
        country: "Chile",
        grape: "Cabernet Sauvignon",
        price: 16,
    },
    {
        id: 6,
        name: "Cabernet Sauvignon Select",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Cabernet Sauvignon, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2017,
        winery: "Gaja",
        country: "Chile",
        grape: "Cabernet Sauvignon",
        price: 33,
    },
    {
        id: 7,
        name: "Merlot Estate",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Merlot, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2012,
        winery: "Penfolds",
        country: "Spain",
        grape: "Merlot",
        price: 57,
    },
    {
        id: 8,
        name: "Cabernet Sauvignon Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Cabernet Sauvignon, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2022,
        winery: "Gaja",
        country: "Australia",
        grape: "Cabernet Sauvignon",
        price: 31,
    },
    {
        id: 9,
        name: "Cabernet Sauvignon Classic",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Cabernet Sauvignon, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2014,
        winery: "Robert Mondavi",
        country: "USA",
        grape: "Cabernet Sauvignon",
        price: 41,
    },
    {
        id: 10,
        name: "Malbec Select",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/672/non_2x/transparent-dark-wine-bottle-with-blank-label-and-burgundy-foil-capsule-seal-png.png",
        description:
            "Un vino tinto elaborado con Malbec, conocido por su sabor y aroma equilibrados.",
        category: "tinto",
        year: 2021,
        winery: "Gaja",
        country: "Australia",
        grape: "Malbec",
        price: 22,
    },
    {
        id: 11,
        name: "Sauvignon Blanc Select",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Sauvignon Blanc, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2015,
        winery: "Robert Mondavi",
        country: "Italy",
        grape: "Sauvignon Blanc",
        price: 29,
    },
    {
        id: 12,
        name: "Riesling Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Riesling, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2020,
        winery: "Antinori",
        country: "Australia",
        grape: "Riesling",
        price: 19,
    },
    {
        id: 13,
        name: "Sauvignon Blanc Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Sauvignon Blanc, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2012,
        winery: "Gaja",
        country: "USA",
        grape: "Sauvignon Blanc",
        price: 57,
    },
    {
        id: 14,
        name: "Riesling Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Riesling, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2021,
        winery: "Beringer",
        country: "Chile",
        grape: "Riesling",
        price: 49,
    },
    {
        id: 15,
        name: "Sauvignon Blanc Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Sauvignon Blanc, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2014,
        winery: "Gaja",
        country: "Argentina",
        grape: "Sauvignon Blanc",
        price: 40,
    },
    {
        id: 16,
        name: "Chardonnay Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Chardonnay, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2014,
        winery: "Robert Mondavi",
        country: "Chile",
        grape: "Chardonnay",
        price: 43,
    },
    {
        id: 17,
        name: "Chardonnay Classic",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Chardonnay, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2018,
        winery: "Beringer",
        country: "Australia",
        grape: "Chardonnay",
        price: 17,
    },
    {
        id: 18,
        name: "Sauvignon Blanc Estate",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Sauvignon Blanc, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2022,
        winery: "Gaja",
        country: "Chile",
        grape: "Sauvignon Blanc",
        price: 24,
    },
    {
        id: 19,
        name: "Pinot Grigio Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Pinot Grigio, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2021,
        winery: "Gaja",
        country: "France",
        grape: "Pinot Grigio",
        price: 59,
    },
    {
        id: 20,
        name: "Viognier Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/016/475/594/non_2x/transparent-white-wine-bottle-with-blank-label-and-gold-foil-capsule-seal-png.png",
        description:
            "Un vino blanco elaborado con Viognier, conocido por su sabor y aroma equilibrados.",
        category: "blanco",
        year: 2018,
        winery: "Penfolds",
        country: "Spain",
        grape: "Viognier",
        price: 59,
    },
    {
        id: 21,
        name: "Champagne Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Champagne, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2016,
        winery: "Concha y Toro",
        country: "France",
        grape: "Champagne",
        price: 41,
    },
    {
        id: 22,
        name: "Prosecco Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Prosecco, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2013,
        winery: "Antinori",
        country: "Australia",
        grape: "Prosecco",
        price: 24,
    },
    {
        id: 23,
        name: "Cava Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Cava, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2016,
        winery: "Concha y Toro",
        country: "Argentina",
        grape: "Cava",
        price: 24,
    },
    {
        id: 24,
        name: "Sparkling Rosé Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Sparkling Rosé, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2012,
        winery: "Beringer",
        country: "Spain",
        grape: "Sparkling Rosé",
        price: 35,
    },
    {
        id: 25,
        name: "Prosecco Classic",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Prosecco, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2018,
        winery: "Torres",
        country: "Australia",
        grape: "Prosecco",
        price: 34,
    },
    {
        id: 26,
        name: "Franciacorta Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Franciacorta, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2015,
        winery: "Beringer",
        country: "Italy",
        grape: "Franciacorta",
        price: 20,
    },
    {
        id: 27,
        name: "Cava Estate",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Cava, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2021,
        winery: "Torres",
        country: "Chile",
        grape: "Cava",
        price: 16,
    },
    {
        id: 28,
        name: "Champagne Classic",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Champagne, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2012,
        winery: "Torres",
        country: "Spain",
        grape: "Champagne",
        price: 58,
    },
    {
        id: 29,
        name: "Prosecco Estate",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Prosecco, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2013,
        winery: "Concha y Toro",
        country: "Australia",
        grape: "Prosecco",
        price: 13,
    },
    {
        id: 30,
        name: "Champagne Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/049/949/580/non_2x/elegant-sparkling-wine-bottle-displayed-on-a-table-cut-out-transparent-png.png",
        description:
            "Un vino espumoso elaborado con Champagne, conocido por su sabor y aroma equilibrados.",
        category: "espumante",
        year: 2018,
        winery: "Robert Mondavi",
        country: "Italy",
        grape: "Champagne",
        price: 42,
    },
    {
        id: 31,
        name: "Rosé Estate",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description:
            "Un vino rosado fresco y vibrante, perfecto para las tardes de verano.",
        category: "rosado",
        year: 2022,
        winery: "Chateau Miraval",
        country: "France",
        grape: "Grenache",
        price: 28,
    },
    {
        id: 32,
        name: "Pink Pinot",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description:
            "Un rosado delicado con notas de frutilla y pétalos de rosa.",
        category: "rosado",
        year: 2021,
        winery: "Whispering Angel",
        country: "France",
        grape: "Pinot Noir",
        price: 35,
    },
    {
        id: 33,
        name: "Blush Rosé",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description: "Un rosado ligero y afrutado, equilibrado y refrescante.",
        category: "rosado",
        year: 2020,
        winery: "Beringer",
        country: "USA",
        grape: "Zinfandel",
        price: 22,
    },
    {
        id: 34,
        name: "Sunset Rosé",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description:
            "Un rosado brillante y aromático con notas cítricas y de bayas.",
        category: "rosado",
        year: 2019,
        winery: "Torres",
        country: "Spain",
        grape: "Tempranillo",
        price: 25,
    },
    {
        id: 35,
        name: "Rosé Reserve",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description: "Un rosado elegante con aroma floral y un final fresco.",
        category: "rosado",
        year: 2021,
        winery: "Antinori",
        country: "Italy",
        grape: "Sangiovese",
        price: 30,
    },
    {
        id: 36,
        name: "Garden Rosé",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description:
            "Un rosado fresco y jugoso, ideal para reuniones al aire libre.",
        category: "rosado",
        year: 2022,
        winery: "Robert Mondavi",
        country: "USA",
        grape: "Syrah",
        price: 27,
    },
    {
        id: 37,
        name: "Berry Rosé",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description: "Rosado con intensos sabores a bayas y un final suave.",
        category: "rosado",
        year: 2020,
        winery: "Gaja",
        country: "Italy",
        grape: "Nebbiolo",
        price: 34,
    },
    {
        id: 38,
        name: "Classic Rosé",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description:
            "Un rosado seco clásico con acidez equilibrada y notas frutales.",
        category: "rosado",
        year: 2018,
        winery: "Penfolds",
        country: "Australia",
        grape: "Shiraz",
        price: 29,
    },
    {
        id: 39,
        name: "Rosé Vintage",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description: "Rosado añejo con aromas delicados y sabor refrescante.",
        category: "rosado",
        year: 2017,
        winery: "Beringer",
        country: "Chile",
        grape: "Cabernet Franc",
        price: 26,
    },
    {
        id: 40,
        name: "Summer Rosé",
        image: "https://static.vecteezy.com/system/resources/previews/039/658/409/non_2x/ai-generated-rose-wine-bottle-with-blank-label-mockup-free-png.png",
        description:
            "Rosado ligero, perfecto para días de verano con notas de sandía.",
        category: "rosado",
        year: 2022,
        winery: "Concha y Toro",
        country: "Chile",
        grape: "Carignan",
        price: 24,
    },
];

export default wines;
